### ISSUE TITLE
The GWTD01 and 02 are missing

### ISSUE THREAD

**Issue by ePascalC** [wppolyglots/wptranslationday.org#16]
It seems there is no link anymore to the previous GWTD archived sites. Any reason ?

**Comment by mrxkon** [comment]
There are links in the sub menu under 'The Event'. Aren't they showing for you ? "WPTD1 WPTD2"

**Comment by ePascalC** [comment]
Nope, nothing on click, nothing on hover over.
Win10 and Chrome

**Comment by ePascalC** [comment]
Hard refresh as you suggested worked ... Thanks.
