### ISSUE TITLE
Social mentions wrong order

### ISSUE THREAD

**Issue by ePascalC** [wppolyglots/wptranslationday.org#17]
The order of the social mentions seem completely random. Can they be put by date?

**Comment by mrxkon** [comment]
I was thinking about that too, I'll have to go through Tagregators code again to see what's up.

Dearly noted!

**Comment by ePascalC** [comment]
Some further testing:
- http://wptranslationday.org/wp-json/tagregator/v1/items/?hashtags=WPTranslationDay is showing the records in the correct order and that's where the js seems to take the data from.
- A var_dump of $items just before the end of function rest_get_items in /classes/tggr-shortcode-tagregator.php is having the correct order

**Comment by ePascalC** [comment]
THIS PROBLEM IS ONLY ON CHROME (Win10) !!! Order is fine on Internet Eplorer 11 and Edge

**Comment by mrxkon** [comment]
Changed the social plugin.
