### ISSUE TITLE
Changing Page Title removes the whole page from landing page

### ISSUE THREAD

**Issue by ePascalC** [wppolyglots/wptranslationday.org#7]
Page: https://wptranslationday.org/wp-admin/post.php?post=8&action=edit

The title needs to be changed from 'Where is GWTD3?' to 'Where is WPTranslationDay 3?'. But doing that the landing page does not show the page anymore. I tried to delete the cache but no result.
What is the dependency between landing page and the real pages? And how to change them ?
Note that I will also have to change the permalink from https://wptranslationday.org/where-is-gwtd3/ to https://wptranslationday.org/where-is-wptranslationday-3/

This whole scenario will also be repeated for the other page 'What is GWTD3?'

Please let me know how to proceed.

**Comment by ePascalC** [comment]
I see the template file now. Can you please adapt:
$page = get_page_by_title( 'What is GWTD3?' );

And use e.g. the slug (that should be changed to 'where-is-wptranslationday-3') or the post ID if it's easier/better.

**Comment by mrxkon** [comment]
Yes I'm making a fix now. It was like that for the migration process and as the titles where pre-defined for the landing page I didn't think of changing them. 

I'll implement the ID as it will never change.
